import type { Meta, StoryObj } from "@storybook/react-vite";
import { Briefcase, FileText, Layers } from "lucide-react";
import { Button, FileDropzone, FitBadge, NavigationItem, Pill, ProgressBar, SectionCard, StatusBadge } from "./components";

const meta = { title: "Components/Product primitives", tags: ["autodocs"] } satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;

export const CoreSet: Story = { render: () => <main className="docs"><div className="eyebrow">8 reusable primitives</div><h1>Product components</h1><p className="docs-lead">Компоненты извлечены из повторяющихся паттернов студенческого, employer и career-center интерфейсов.</p><section className="docs-section"><h2>Buttons</h2><div className="demo row"><Button>Получить AI-рекомендации</Button><Button variant="secondary">Отмена</Button><Button variant="ghost">Подробнее</Button><Button disabled>Недоступно</Button></div></section><section className="docs-section"><h2>Badges & pills</h2><div className="demo row"><Pill>Python</Pill><Pill>SQL</Pill><StatusBadge tone="success">Утверждено</StatusBadge><StatusBadge tone="warning">Ожидает</StatusBadge><FitBadge value={75}/></div></section><section className="docs-section"><h2>Section card</h2><SectionCard title="Ближайшие мероприятия" icon={<FileText size={18}/>} action={<Button variant="ghost">Все события</Button>}><p style={{color:"#6B7280",margin:0}}>Карточка — основная единица группировки контента во всех трёх ролях.</p></SectionCard></section><section className="docs-section"><h2>Progress</h2><div className="demo stack"><ProgressBar value={64} label="Explorer → Achiever"/><ProgressBar value={88} label="Заполнение профиля"/></div></section><section className="docs-section"><h2>Navigation</h2><div className="demo stack" style={{maxWidth:320}}><NavigationItem label="Главная" active icon={<Layers/>}/><NavigationItem label="Вакансии" icon={<Briefcase/>}/><NavigationItem label="CV Tailor (AI)" icon={<FileText/>}/></div></section><section className="docs-section"><h2>File dropzone</h2><div className="grid"><FileDropzone/><FileDropzone state="ready" fileName="cv_margarita.pdf"/><FileDropzone state="extracting" fileName="cv_margarita.pdf"/></div></section></main> };
